### ISSUE TITLE
Wrong mask

### ISSUE THREAD

**Issue by embs-be** [sparkfun/MMA8452_Accelerometer#12]
https://github.com/sparkfun/MMA8452_Accelerometer/blob/master/Firmware/libraries/SFE_MMA8452Q/SFE_MMA8452Q.cpp#L116

should be ctrl &= 0xC7; 

ODR takes 3 bytes :)

**Comment by hermanbanken** [comment]
Think that this is fixed. Right? Looking at [Libraries/Arduino/src/SparkFun_MMA8452Q.cpp#L118](/sparkfun/MMA8452_Accelerometer/blob/master/Libraries/Arduino/src/SparkFun_MMA8452Q.cpp#L118) that is...

Just reporting this because of the Boy Scout rule :+1: I was browsing this library for a new project. Looks great!

**Comment by embs-be** [comment]
Nope. Old code still there.

**Comment by jimblom** [comment]
Pulled in the latest version of the [Arduino Library](https://github.com/sparkfun/SparkFun_MMA8452Q_Arduino_Library). Should be fixed now.
